# Generated by Django 4.2.5 on 2023-10-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepressionQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q2', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q3', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q4', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q5', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q6', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q7', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q8', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q9', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q10', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q11', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q12', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q13', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q14', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q15', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q16', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q17', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q18', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q19', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q20', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q21', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q22', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q23', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q24', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q25', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q26', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q27', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q28', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q29', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q30', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q31', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q32', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q33', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q34', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q35', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q36', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q37', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q38', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q39', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q40', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q41', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
                ('q42', models.IntegerField(choices=[(1, 'Did not apply to me at all'), (2, 'Applied to me to some degree, or some of the time'), (3, 'Applied to me to a considerable degree, or a good part of the time'), (4, 'Applied to me very much, or most of the time')])),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfAssessment', models.DateField()),
                ('Scores', models.IntegerField()),
                ('Username', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=10)),
                ('Diagnosis', models.CharField(max_length=150)),
                ('Severity', models.IntegerField()),
            ],
        ),
    ]
