# Generated by Django 4.2.5 on 2023-11-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_remove_account_user_delete_depressionquestionnaire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentalHealthDiagnosis',
        ),
        migrations.RemoveField(
            model_name='mentalhealthassessment',
            name='DateOfAssessment',
        ),
        migrations.RemoveField(
            model_name='mentalhealthassessment',
            name='Scores',
        ),
    ]
