# Generated by Django 4.2.5 on 2023-11-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_delete_mentalhealthdiagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalhealthassessment',
            name='Gender',
        ),
        migrations.AddField(
            model_name='mentalhealthassessment',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=6),
        ),
    ]
